name: Upload Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies in hunter
        run: |
          cd hunter
          npm install

      - name: Build React App
        run: |
          cd hunter
          export USER_ID=${{ secrets.REACT_APP_EMAILJS_USER_ID }}
          npm run build

      - name: Deploy static assets to S3 bucket
        run: aws s3 sync ./hunter/build/ s3://${{ secrets.BUCKET }} --delete
